'use client';

import { createContext, useContext, useEffect, useState } from 'react';
import type { ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'mwr' | 'gu' | 'sa';

const STORAGE_KEY = 'shri-ayurved-language';
const SUPPORTED_LANGUAGES: Language[] = ['en', 'hi', 'mr', 'mwr', 'gu', 'sa'];
const isLanguage = (value: string): value is Language => SUPPORTED_LANGUAGES.includes(value as Language);

const hindiTranslations: Record<string, string> = {
  'Purity Is Our Pride • Fast Worldwide Handling • Traditional Sourcing': 'शुद्धता हमारी पहचान • दुनिया भर में तेज़ डिलीवरी • पारंपरिक तरीके से चुने उत्पाद',
  'Search by Formulation, Herb, Ritual...': 'उत्पाद, जड़ी-बूटी या पूजा सामग्री खोजें...',
  Philosophy: 'हमारी सोच',
  Shop: 'खरीदें',
  'Custom Kit': 'अपनी पूजा किट',
  Language: 'भाषा चुनें',
  'Signed in as': 'लॉग इन हैं:',
  'Account Settings': 'खाते की जानकारी',
  'Order History': 'मेरे ऑर्डर',
  'Saved Addresses': 'मेरे पते',
  'Logged-in Devices': 'लॉग इन डिवाइस',
  'My Reviews': 'मेरी समीक्षाएँ',
  Notifications: 'सूचनाएँ',
  'Sign Out': 'लॉग आउट',
  'Dashboard Menu': 'खाता मेनू',
  'Sign In': 'लॉग इन',
  Home: 'होम',
  Kit: 'किट',
  Wishlist: 'पसंदीदा',
  Cart: 'टोकरी',
  Account: 'खाता',
  'Trusted Ayurvedic products and traditional essentials, selected with care and presented with clear product information.': 'भरोसेमंद आयुर्वेदिक और पूजा के सामान। हर उत्पाद की जानकारी साफ़ और आसान भाषा में।',
  'Quality checked': 'गुणवत्ता की जाँच',
  Explore: 'देखें',
  'Our Philosophy': 'हमारी सोच',
  'Shop Products': 'सामान खरीदें',
  'Custom Kits': 'अपनी पूजा किट',
  Help: 'मदद',
  'Worldwide Shipping': 'दुनिया भर में डिलीवरी',
  'Product Information': 'उत्पाद की जानकारी',
  'Contact Us': 'हमसे संपर्क करें',
  Subscribe: 'अपडेट पाएँ',
  'Get updates about products and custom kits.': 'नए उत्पादों और पूजा किट की जानकारी पाएँ।',
  'Enter your email destination...': 'अपना ईमेल लिखें',
  'Beyond E-Commerce • Pure Sanctuary Framework': 'सिर्फ़ खरीदारी नहीं • भरोसे और शुद्धता का साथ',
  'Traditional knowledge,': 'परंपरागत ज्ञान,',
  'honestly priced': 'उचित दाम पर',
  'for every home.': 'हर घर के लिए।',
  "Welcome to India's most transparent platform for premium Ayurvedic formulations, wild-harvested raw herbs, cold-pressed extraction oils, and sacred ritual artifacts. Designed for seamless use by families, pundits, and spiritual seekers alike.": 'यहाँ आयुर्वेदिक उत्पाद, जड़ी-बूटियाँ, तेल और पूजा का सामान साफ़ जानकारी और उचित दाम पर मिलता है। परिवारों और पूजा करने वालों के लिए आसान खरीदारी।',
  'Build Custom Kit': 'अपनी पूजा किट बनाएँ',
  'Explore Raw Herbs': 'जड़ी-बूटियाँ देखें',
  'Operational Integrity': 'हमारा भरोसा',
  'Verified Sourcing Blueprint': 'सामान कहाँ से आता है',
  'We categorically stand against superlative claims like "Lowest Price" or "Number One in India". We focus entirely on unembellished chemical transparency, hermetic preservation, and certified botanical lineage tracking.': 'हम "सबसे सस्ता" या "भारत में नंबर एक" जैसे दावे नहीं करते। हम उत्पाद की सही जानकारी, सुरक्षित पैकिंग और भरोसेमंद स्रोत पर ध्यान देते हैं।',
  'A Uniquely Structured Experience': 'खरीदारी का आसान अनुभव',
  'Purity and tradition, with clear product details and fair prices.': 'शुद्धता और परंपरा, साफ़ जानकारी और उचित दाम के साथ।',
  'Custom Ritual Box Builder': 'अपनी पूजा किट बनाएँ',
  'Brahman-Verified Layouts': 'पंडितों की सुझाई सूची',
  'Select a verified foundation blueprint designed by expert pandits. Have some items at home? Simply reduce their quantities to exclude them and save. Need extras? Customize instantly.': 'पंडितों की सुझाई पूजा-सामग्री सूची चुनें। घर पर कोई सामान है? उसकी मात्रा कम कर दें। कुछ और चाहिए? अपनी किट में जोड़ें।',
  'Choose Ritual Blueprint Purpose': '1. पूजा का प्रकार चुनें',
  'Customize Box Inventory Elements': '2. पूजा का सामान चुनें',
  'Reset to Pandit Recommended': 'पंडित की सुझाई मात्रा वापस रखें',
  'Pandit Choice': 'पंडित की सलाह',
  'Essential ritual component': 'पूजा के लिए ज़रूरी सामान',
  Modified: 'बदला गया',
  'Excluded (Own at Home)': 'नहीं चाहिए (घर पर है)',
  'Box Manifest Breakdown': 'आपकी किट में',
  'Live visualization of your custom ritual package manifest': 'आपकी चुनी पूजा सामग्री',
  'Ritual Box Base Layout': 'किट की शुरुआती कीमत',
  'All items excluded. Box is currently empty.': 'कोई सामान नहीं चुना गया। किट खाली है।',
  'Estimated Total': 'कुल अनुमानित कीमत',
  'Processing Order...': 'ऑर्डर भेज रहे हैं...',
  'Place Kit Order': 'किट का ऑर्डर दें',
  'Items lowered to zero will not be packed in your container. Perfect if you have brass artifacts or powders remaining from prior home celebrations.': 'जिस सामान की मात्रा शून्य होगी, वह किट में नहीं आएगा। घर पर पहले से मौजूद सामान हटाने के लिए मात्रा कम करें।',
  'Loading ritual box catalog configurations...': 'पूजा किट की जानकारी लोड हो रही है...',
  'Cart Summary': 'आपकी टोकरी',
  'Your Cart': 'आपकी टोकरी',
  'Review your selected products before checkout.': 'ऑर्डर देने से पहले अपना सामान देख लें।',
  Piece: 'वस्तु',
  Pieces: 'वस्तुएँ',
  'Clear Cart': 'टोकरी खाली करें',
  'Your cart is empty': 'आपकी टोकरी खाली है',
  'Proceed to Checkout': 'ऑर्डर आगे बढ़ाएँ',
  Checkout: 'ऑर्डर करें',
  'Explore Collection': 'सामान देखें',
  Search: 'खोजें',
  'Toggle Navigation Menu': 'मेनू खोलें या बंद करें',
  'Mobile primary navigation': 'मुख्य नेविगेशन',
  'Find products by:': 'यहाँ खोजें:',
  'How We Choose Products': 'हम उत्पाद कैसे चुनते हैं',
  'Carefully Sourced Products': 'भरोसेमंद स्रोतों से चुने उत्पाद',
  'We do not make claims like "Lowest Price" or "Number One in India." We share clear product details and choose trusted suppliers.': 'हम "सबसे सस्ता" या "भारत में नंबर एक" जैसे दावे नहीं करते। हम साफ़ जानकारी देते हैं और भरोसेमंद विक्रेताओं से सामान चुनते हैं।',
  'Why Shop With Us': 'हमसे क्यों खरीदें',
  'Traditional Products, Easier to Find': 'परंपरागत सामान अब आसानी से पाएँ',
  'Find Ayurvedic products, herbs, oils, and puja essentials in one place, with clear details and fair prices.': 'आयुर्वेदिक सामान, जड़ी-बूटियाँ, तेल और पूजा की ज़रूरी चीज़ें एक ही जगह, साफ़ जानकारी और उचित दाम पर पाएँ।',
  'Available now': 'अभी उपलब्ध',
  'Our product range': 'हमारे उत्पाद',
  'Browse by category': 'श्रेणी चुनें',
  'Find puja and wellness essentials': 'पूजा और सेहत का सामान देखें',
  'View products': 'उत्पाद देखें',
  'Build a kit that fits your needs': 'अपनी ज़रूरत की किट बनाएँ',
  'Make your puja kit your way:': 'अपनी पूजा किट खुद बनाएँ:',
  'Choose your items and amounts.': 'सामान और उसकी मात्रा चुनें।',
  'Choose the puja items and amounts you need. Leave out anything you already have at home, and see the price update as you make changes.': 'पूजा का सामान और उसकी मात्रा चुनें। जो सामान घर पर है उसे हटा दें। बदलाव के साथ कीमत भी बदलती जाएगी।',
  'Your kit price updates as you change the items and amounts.': 'सामान या मात्रा बदलने पर किट की कीमत भी बदल जाएगी।',
  'Choose puja items': 'पूजा का सामान चुनें',
  'Pick herbs, camphor, oils, wood, or brass items for your kit.': 'अपनी किट के लिए जड़ी-बूटी, कपूर, तेल, लकड़ी या पीतल का सामान चुनें।',
  'Set amounts': 'मात्रा चुनें',
  'Choose how much of each item you need.': 'हर सामान की ज़रूरत के अनुसार मात्रा चुनें।',
  'Delivery to your home': 'घर पर डिलीवरी',
  'Choose your kit and enter your delivery address at checkout.': 'किट चुनें और ऑर्डर देते समय अपना पता भरें।',
  'Loading your puja kit...': 'आपकी पूजा किट लोड हो रही है...',
  'Puja expert suggestions': 'पूजा विशेषज्ञों की सलाह',
  'Build Your Puja Kit': 'अपनी पूजा किट बनाएँ',
  'Choose a list suggested by puja experts. Already have some items? Lower their quantities. Need something else? Add it to your kit.': 'पूजा विशेषज्ञों की सुझाई सूची चुनें। कुछ सामान घर पर है? उसकी मात्रा कम करें। कुछ और चाहिए? उसे किट में जोड़ें।',
  Close: 'बंद करें',
  'Choose a puja': 'पूजा चुनें',
  'Starting price': 'शुरुआती कीमत',
  'Use suggested amounts': 'सुझाई गई मात्रा रखें',
  'Suggested amount': 'सुझाई गई मात्रा',
  'Puja essential': 'पूजा का ज़रूरी सामान',
  Changed: 'बदला गया',
  'Not needed (already at home)': 'ज़रूरत नहीं (घर पर है)',
  'Your kit': 'आपकी किट',
  'Items and amounts you selected': 'आपका चुना सामान और उसकी मात्रा',
  'Kit starting price': 'किट की शुरुआती कीमत',
  Amount: 'मात्रा',
  Custom: 'अपनी पसंद',
  'Your kit is empty.': 'आपकी किट खाली है।',
  'Estimated total': 'कुल अनुमानित कीमत',
  'Placing your order...': 'आपका ऑर्डर भेजा जा रहा है...',
  'Place kit order': 'किट का ऑर्डर दें',
  'Items set to zero will not be packed. Remove anything you already have at home.': 'जिस सामान की मात्रा शून्य होगी, वह किट में नहीं आएगा। घर पर मौजूद सामान हटा दें।',
  'Browse our products and add something you like.': 'हमारे उत्पाद देखें और पसंद का सामान जोड़ें।',
  Unlocked: 'मिल गया',
  'Free shipping': 'मुफ़्त डिलीवरी',
  Add: 'जोड़ें',
  'for free delivery': 'और डिलीवरी मुफ़्त पाएँ',
  each: 'प्रति वस्तु',
  Subtotal: 'सामान की कीमत',
  Delivery: 'डिलीवरी',
  Free: 'मुफ़्त',
  Total: 'कुल',
  'Taxes included': 'टैक्स शामिल हैं',
  'Secure payment': 'सुरक्षित भुगतान',
  'Careful packing and delivery': 'सुरक्षित पैकिंग और डिलीवरी',
  'Clear all items from cart': 'टोकरी का सारा सामान हटाएँ',
  'Product name': 'उत्पाद का नाम', 'Health concern': 'स्वास्थ्य समस्या', Herb: 'जड़ी-बूटी', Puja: 'पूजा',
  'Sanskrit name': 'संस्कृत नाम', 'Hindi name': 'हिंदी नाम', 'English name': 'अंग्रेज़ी नाम',
  'How do you keep prices fair?': 'कीमतें उचित कैसे रखते हैं?',
  'We work with growers and local makers where possible, helping us offer good products at fair prices.': 'हम जहाँ संभव हो, किसानों और स्थानीय कारीगरों से सीधे सामान लेते हैं ताकि उचित दाम रख सकें।',
  'Can I choose what goes in my puja kit?': 'क्या मैं अपनी पूजा किट का सामान चुन सकता हूँ?',
  'Yes. Choose the items and amounts you need. Leave out anything you already have at home.': 'हाँ। अपनी ज़रूरत का सामान और मात्रा चुनें। जो सामान घर पर है, उसे हटा दें।',
  'Where can I find certificates and customer reviews?': 'प्रमाणपत्र और ग्राहक की राय कहाँ मिलेगी?',
  'We will show product certificates and customer reviews here once they are available.': 'उत्पाद के प्रमाणपत्र और ग्राहक की राय उपलब्ध होने पर यहाँ दिखाएँगे।',
  'Our products': 'हमारे उत्पाद', 'Popular products': 'लोकप्रिय उत्पाद', All: 'सभी',
  'Loading products...': 'उत्पाद लोड हो रहे हैं...', 'Products could not be loaded': 'उत्पाद लोड नहीं हो सके',
  'Please try again in a moment.': 'कृपया थोड़ी देर बाद फिर कोशिश करें।',
  'No products found in this category.': 'इस श्रेणी में कोई उत्पाद नहीं मिला।',
  'Product image unavailable': 'उत्पाद की तस्वीर उपलब्ध नहीं है', 'Other products': 'अन्य उत्पाद', Price: 'कीमत', 'Add to cart': 'टोकरी में जोड़ें',
  'Made for everyone': 'सबके लिए', 'Easy to use for every family': 'हर परिवार के लिए आसान',
  'Find puja and wellness products with clear names, prices, and details.': 'पूजा और सेहत के उत्पाद साफ़ नाम, दाम और जानकारी के साथ पाएँ।',
  'For homes, puja, and everyday wellness': 'घर, पूजा और रोज़मर्रा की सेहत के लिए',
  'Families who perform puja at home': 'घर पर पूजा करने वाले परिवार', 'Priests and puja guides': 'पुजारी और पूजा करवाने वाले',
  'People who use Ayurvedic products': 'आयुर्वेदिक उत्पाद इस्तेमाल करने वाले', 'Older adults and spiritual learners': 'बुज़ुर्ग और आध्यात्मिक ज्ञान पाने वाले',
  'Families looking for fair prices': 'उचित दाम खोजने वाले परिवार', 'Product checks': 'उत्पाद की जाँच',
  'Clear product information': 'उत्पाद की साफ़ जानकारी',
  'We only share details that have been checked. More information will be added when it is available.': 'हम जाँची हुई जानकारी ही साझा करते हैं। बाकी जानकारी मिलते ही जोड़ेंगे।',
  'AYUSH licence': 'आयुष लाइसेंस', 'FSSAI certificate': 'एफ़एसएसएआई प्रमाणपत्र', 'Lab test reports': 'लैब जाँच की रिपोर्ट',
  'Packing and delivery': 'पैकिंग और डिलीवरी', 'Certificate details will be added when available.': 'प्रमाणपत्र की जानकारी उपलब्ध होने पर जोड़ी जाएगी।',
  'Lab report details will be added when available.': 'लैब रिपोर्ट की जानकारी उपलब्ध होने पर जोड़ी जाएगी।',
  'Delivery information will be shown with your order.': 'डिलीवरी की जानकारी आपके ऑर्डर में दिखेगी।',
  'Customer reviews will appear here when available.': 'ग्राहकों की राय उपलब्ध होने पर यहाँ दिखेगी।',
  'Common questions': 'आम सवाल', 'Simple answers about prices, products, and custom puja kits.': 'कीमत, उत्पाद और पूजा किट के आसान जवाब।',
  'Get product updates': 'उत्पादों की नई जानकारी पाएँ',
  'Sign up to hear about new products and seasonal collections.': 'नए उत्पादों और मौसम के खास संग्रह की जानकारी पाएँ।',
  'Email address': 'ईमेल पता', 'Enter your email': 'अपना ईमेल लिखें',
};

const marathiTranslations: Record<string, string> = {
  'Purity Is Our Pride • Fast Worldwide Handling • Traditional Sourcing': 'शुद्धता हीच आमची ओळख • जगभर जलद डिलिव्हरी • पारंपरिक पद्धतीने निवडलेली उत्पादने',
  'Search by Formulation, Herb, Ritual...': 'उत्पादन, औषधी वनस्पती किंवा पूजेचे साहित्य शोधा...',
  Philosophy: 'आमची विचारधारा', Shop: 'खरेदी', 'Custom Kit': 'पूजा साहित्याची किट', Language: 'भाषा निवडा',
  'Signed in as': 'लॉग इन केले आहे:', 'Account Settings': 'खात्याची माहिती', 'Order History': 'माझ्या ऑर्डर्स',
  'Saved Addresses': 'माझे पत्ते', 'Logged-in Devices': 'लॉग इन केलेली उपकरणे', 'My Reviews': 'माझी मतं',
  Notifications: 'सूचना', 'Sign Out': 'लॉग आउट', 'Dashboard Menu': 'खाते मेनू', 'Sign In': 'लॉग इन',
  Home: 'मुख्यपृष्ठ', Kit: 'किट', Wishlist: 'आवडते', Cart: 'पिशवी', Account: 'खाते',
  'Build Custom Kit': 'आपली पूजा किट तयार करा', 'Explore Raw Herbs': 'औषधी वनस्पती पाहा',
  'Build Your Puja Kit': 'आपली पूजा किट तयार करा', 'Choose a puja': 'पूजा निवडा', 'Choose puja items': 'पूजेचे साहित्य निवडा',
  'Use suggested amounts': 'सुचवलेले प्रमाण वापरा', 'Suggested amount': 'सुचवलेले प्रमाण', 'Your kit': 'आपली किट',
  'Estimated total': 'अंदाजे एकूण', 'Place kit order': 'किटची ऑर्डर द्या', 'Your kit is empty.': 'आपली किट रिकामी आहे.',
  'Your Cart': 'आपली पिशवी', 'Cart Summary': 'पिशवीचा तपशील', 'Review your selected products before checkout.': 'ऑर्डर देण्यापूर्वी निवडलेली उत्पादने तपासा.',
  Piece: 'वस्तू', Pieces: 'वस्तू', 'Clear Cart': 'पिशवी रिकामी करा', 'Your cart is empty': 'आपली पिशवी रिकामी आहे.',
  'Explore Collection': 'उत्पादने पाहा', 'Proceed to Checkout': 'ऑर्डर पुढे सुरू करा', Checkout: 'ऑर्डर करा',
  Subtotal: 'उपएकूण', Delivery: 'डिलिव्हरी', Total: 'एकूण', 'Free shipping': 'मोफत डिलिव्हरी',
  'Taxes included': 'कर समाविष्ट', 'Secure payment': 'सुरक्षित पेमेंट', 'Careful packing and delivery': 'सुरक्षित पॅकिंग आणि डिलिव्हरी',
  'Product name': 'उत्पादनाचे नाव', 'Health concern': 'आरोग्याची समस्या', Herb: 'औषधी वनस्पती', Puja: 'पूजा',
  'Sanskrit name': 'संस्कृत नाव', 'Hindi name': 'हिंदी नाव', 'English name': 'इंग्रजी नाव',
  'How do you keep prices fair?': 'किंमती योग्य कशा ठेवता?',
  'We work with growers and local makers where possible, helping us offer good products at fair prices.': 'शक्य असेल तेथे आम्ही शेतकरी आणि स्थानिक कारागिरांकडून थेट वस्तू घेतो, त्यामुळे योग्य किंमती ठेवता येतात.',
  'Can I choose what goes in my puja kit?': 'माझ्या पूजा किटमध्ये काय असेल हे मी ठरवू शकतो का?',
  'Yes. Choose the items and amounts you need. Leave out anything you already have at home.': 'हो. गरजेच्या वस्तू आणि त्यांचे प्रमाण निवडा. घरात आधीपासून असलेल्या वस्तू वगळा.',
  'Where can I find certificates and customer reviews?': 'प्रमाणपत्रे आणि ग्राहकांची मते कुठे पाहू?',
  'We will show product certificates and customer reviews here once they are available.': 'उत्पादनांची प्रमाणपत्रे आणि ग्राहकांची मते उपलब्ध झाल्यावर येथे दाखवू.',
  'Our products': 'आमची उत्पादने', 'Popular products': 'लोकप्रिय उत्पादने', All: 'सर्व',
  'Loading products...': 'उत्पादने लोड होत आहेत...', 'Products could not be loaded': 'उत्पादने दाखवता आली नाहीत',
  'Please try again in a moment.': 'कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.', 'No products found in this category.': 'या प्रकारात उत्पादने आढळली नाहीत.',
  'Product image unavailable': 'उत्पादनाचे छायाचित्र उपलब्ध नाही', 'Other products': 'इतर उत्पादने', Price: 'किंमत', 'Add to cart': 'पिशवीत जोडा',
  'Made for everyone': 'सर्वांसाठी', 'Easy to use for every family': 'प्रत्येक कुटुंबासाठी सोपे',
  'Find puja and wellness products with clear names, prices, and details.': 'पूजा आणि आरोग्याची उत्पादने स्पष्ट नावे, किंमती आणि माहितीसह पाहा.',
  'For homes, puja, and everyday wellness': 'घर, पूजा आणि रोजच्या आरोग्यासाठी',
  'Families who perform puja at home': 'घरी पूजा करणारी कुटुंबे', 'Priests and puja guides': 'पुरोहित आणि पूजा मार्गदर्शक',
  'People who use Ayurvedic products': 'आयुर्वेदिक उत्पादने वापरणारे', 'Older adults and spiritual learners': 'ज्येष्ठ नागरिक आणि आध्यात्मिक अभ्यासक',
  'Families looking for fair prices': 'योग्य किंमती शोधणारी कुटुंबे', 'Product checks': 'उत्पादनांची तपासणी',
  'Clear product information': 'उत्पादनांची स्पष्ट माहिती',
  'We only share details that have been checked. More information will be added when it is available.': 'तपासलेली माहितीच आम्ही देतो. अधिक माहिती उपलब्ध झाल्यावर येथे जोडू.',
  'AYUSH licence': 'आयुष परवाना', 'FSSAI certificate': 'एफएसएसएआय प्रमाणपत्र', 'Lab test reports': 'प्रयोगशाळेचे अहवाल',
  'Packing and delivery': 'पॅकिंग आणि डिलिव्हरी', 'Certificate details will be added when available.': 'प्रमाणपत्राची माहिती उपलब्ध झाल्यावर जोडू.',
  'Lab report details will be added when available.': 'प्रयोगशाळेची माहिती उपलब्ध झाल्यावर जोडू.',
  'Delivery information will be shown with your order.': 'डिलिव्हरीची माहिती तुमच्या ऑर्डरमध्ये दिसेल.',
  'Customer reviews will appear here when available.': 'ग्राहकांची मते उपलब्ध झाल्यावर येथे दिसतील.',
  'Common questions': 'नेहमीचे प्रश्न', 'Simple answers about prices, products, and custom puja kits.': 'किंमती, उत्पादने आणि पूजा किटबद्दल सोपी उत्तरे.',
  'Get product updates': 'उत्पादनांच्या बातम्या मिळवा', 'Sign up to hear about new products and seasonal collections.': 'नवीन उत्पादने आणि हंगामी संग्रहाबद्दल जाणून घ्या.',
  'Email address': 'ईमेल पत्ता', 'Enter your email': 'तुमचा ईमेल लिहा',
  'Our product range': 'आमची उत्पादने', 'Browse by category': 'प्रकारानुसार पाहा', 'Find puja and wellness essentials': 'पूजा आणि आरोग्याचे सामान पाहा',
  'View products': 'उत्पादने पाहा', 'Build a kit that fits your needs': 'तुमच्या गरजेनुसार किट बनवा',
  'Make your puja kit your way:': 'तुमची पूजा किट स्वतः बनवा:', 'Choose your items and amounts.': 'वस्तू आणि त्यांचे प्रमाण निवडा.',
  'Choose the puja items and amounts you need. Leave out anything you already have at home, and see the price update as you make changes.': 'पूजेच्या वस्तू आणि त्यांचे प्रमाण निवडा. घरात असलेल्या वस्तू वगळा. बदल केल्यावर किंमतही बदलेल.',
  'Your kit price updates as you change the items and amounts.': 'वस्तू किंवा प्रमाण बदलल्यावर किटची किंमत बदलेल.',
  'Pick herbs, camphor, oils, wood, or brass items for your kit.': 'किटसाठी वनस्पती, कापूर, तेल, लाकूड किंवा पितळेच्या वस्तू निवडा.',
  'Set amounts': 'प्रमाण ठरवा', 'Choose how much of each item you need.': 'प्रत्येक वस्तूचे आवश्यक प्रमाण निवडा.',
  'Delivery to your home': 'घरी डिलिव्हरी', 'Choose your kit and enter your delivery address at checkout.': 'किट निवडा आणि ऑर्डर करताना पत्ता भरा.',
  'Choose a list suggested by puja experts. Already have some items? Lower their quantities. Need something else? Add it to your kit.': 'पूजा तज्ज्ञांनी सुचवलेली यादी निवडा. काही वस्तू घरी आहेत? त्यांचे प्रमाण कमी करा. आणखी काही हवे? किटमध्ये जोडा.',
  'Puja expert suggestions': 'पूजा तज्ज्ञांच्या सूचना', 'Loading your puja kit...': 'तुमची पूजा किट लोड होत आहे...',
  'Starting price': 'सुरुवातीची किंमत', 'Puja essential': 'पूजेसाठी आवश्यक वस्तू', Changed: 'बदलले',
  'Not needed (already at home)': 'नको (घरी उपलब्ध)', 'Items and amounts you selected': 'तुम्ही निवडलेल्या वस्तू आणि प्रमाण',
  'Kit starting price': 'किटची सुरुवातीची किंमत', Amount: 'प्रमाण', Custom: 'तुमच्या पसंतीचे',
  'Placing your order...': 'तुमची ऑर्डर पाठवत आहोत...',
  'Items set to zero will not be packed. Remove anything you already have at home.': 'प्रमाण शून्य असलेल्या वस्तू किटमध्ये येणार नाहीत. घरी असलेल्या वस्तू वगळा.',
  'Browse our products and add something you like.': 'उत्पादने पाहा आणि आवडलेली वस्तू जोडा.', Unlocked: 'मिळाले',
  'for free delivery': 'आणि डिलिव्हरी मोफत मिळवा', each: 'प्रति वस्तू', Free: 'मोफत', 'Clear all items from cart': 'पिशवीतील सर्व वस्तू काढा',
};

const marwariTranslations: Record<string, string> = {
  'Purity Is Our Pride • Fast Worldwide Handling • Traditional Sourcing': 'शुद्धता म्हारी पहचान • दुनिया भर में जल्दी डिलिवरी • रीति सूं चुना सामान',
  'Search by Formulation, Herb, Ritual...': 'सामान, जड़ी-बूटी अर पूजा रो सामान खोजो...',
  Philosophy: 'म्हारी बात', Shop: 'खरीदो', 'Custom Kit': 'अपणी पूजा किट', Language: 'भासा चुनो',
  'Signed in as': 'लॉग इन हो:', 'Account Settings': 'खाते री जानकारी', 'Order History': 'म्हारा ऑर्डर',
  'Saved Addresses': 'म्हारा पता', 'Logged-in Devices': 'लॉग इन डिवाइस', 'My Reviews': 'म्हारी राय',
  Notifications: 'खबर', 'Sign Out': 'बाहर जावो', 'Dashboard Menu': 'खाता मेनू', 'Sign In': 'लॉग इन',
  Home: 'घर', Kit: 'किट', Wishlist: 'पसंद', Cart: 'थैली', Account: 'खातो',
  'Build Custom Kit': 'अपणी पूजा किट बनावो', 'Explore Raw Herbs': 'जड़ी-बूटी देखो',
  'Build Your Puja Kit': 'अपणी पूजा किट बनावो', 'Choose a puja': 'पूजा चुनो', 'Choose puja items': 'पूजा रो सामान चुनो',
  'Use suggested amounts': 'बताई मात्रा राखो', 'Suggested amount': 'बताई मात्रा', 'Your kit': 'थारी किट',
  'Estimated total': 'लगभग कुल', 'Place kit order': 'किट रो ऑर्डर करो', 'Your kit is empty.': 'थारी किट खाली है।',
  'Your Cart': 'थारी थैली', 'Cart Summary': 'थैली रो ब्यौरो', 'Review your selected products before checkout.': 'ऑर्डर करबा सूं पैली चुना सामान देखो।',
  Piece: 'चीज़', Pieces: 'चीज़ां', 'Clear Cart': 'थैली खाली करो', 'Your cart is empty': 'थारी थैली खाली है।',
  'Explore Collection': 'सामान देखो', 'Proceed to Checkout': 'ऑर्डर आगे बढ़ावो', Checkout: 'ऑर्डर करो',
  Subtotal: 'सामान री कीमत', Delivery: 'डिलिवरी', Total: 'कुल', 'Free shipping': 'मुफ्त डिलिवरी',
  'Taxes included': 'टैक्स शामिल', 'Secure payment': 'सुरक्षित पेमेंट', 'Careful packing and delivery': 'सुरक्षित पैकिंग अर डिलिवरी',
  'Product name': 'सामान रो नाम', 'Health concern': 'सेहत री परेशानी', Herb: 'जड़ी-बूटी', Puja: 'पूजा',
  'Sanskrit name': 'संस्कृत नाम', 'Hindi name': 'हिंदी नाम', 'English name': 'अंग्रेजी नाम',
  'How do you keep prices fair?': 'भाव ठीक कियां राखो हो?',
  'We work with growers and local makers where possible, helping us offer good products at fair prices.': 'जितणो बने, हम किसान अर स्थानीय कारीगरां सूं सीधो सामान लेवां, जिण सूं भाव ठीक राख सकां।',
  'Can I choose what goes in my puja kit?': 'म्हारी पूजा किट में क्यूं सामान हो, ई मैं चुन सकूं?',
  'Yes. Choose the items and amounts you need. Leave out anything you already have at home.': 'हां। जरूरत रो सामान अर मात्रा चुनो। घर में जो हो, उणने छोड़ दो।',
  'Where can I find certificates and customer reviews?': 'प्रमाण-पत्र अर ग्राहकां री राय कठे देखूं?',
  'We will show product certificates and customer reviews here once they are available.': 'प्रमाण-पत्र अर ग्राहकां री राय मिलते ई इठे दिखावांला।',
  'Our products': 'म्हारो सामान', 'Popular products': 'पसंद रो सामान', All: 'सगळो',
  'Loading products...': 'सामान खुलै है...', 'Products could not be loaded': 'सामान ना खुल्यो',
  'Please try again in a moment.': 'थोड़ी देर बाद फेर कोशिश करो।', 'No products found in this category.': 'ई किस्म रो सामान ना मिल्यो।',
  'Product image unavailable': 'सामान री फोटो ना है', 'Other products': 'दूजो सामान', Price: 'भाव', 'Add to cart': 'थैली में डालो',
  'Made for everyone': 'सब वास्ते', 'Easy to use for every family': 'हर घर वास्ते आसान',
  'Find puja and wellness products with clear names, prices, and details.': 'पूजा अर सेहत रो सामान साफ नाम, भाव अर जानकारी संग देखो।',
  'For homes, puja, and everyday wellness': 'घर, पूजा अर रोज री सेहत वास्ते',
  'Families who perform puja at home': 'घर में पूजा करबा वाला घर', 'Priests and puja guides': 'पुजारी अर पूजा बतावण वाला',
  'People who use Ayurvedic products': 'आयुर्वेदिक सामान लेबा वाला', 'Older adults and spiritual learners': 'बुजुर्ग अर भक्ति सीखण वाला',
  'Families looking for fair prices': 'ठीक भाव खोजण वाला घर', 'Product checks': 'सामान री जांच',
  'Clear product information': 'सामान री साफ जानकारी',
  'We only share details that have been checked. More information will be added when it is available.': 'जांची हुई जानकारी ई देवां। बाकी जानकारी मिले तो जोड़ांला।',
  'AYUSH licence': 'आयुष लाइसेंस', 'FSSAI certificate': 'एफएसएसएआई प्रमाण-पत्र', 'Lab test reports': 'जांच री रिपोर्ट',
  'Packing and delivery': 'पैकिंग अर डिलिवरी', 'Certificate details will be added when available.': 'प्रमाण-पत्र री जानकारी मिलते ई जोड़ांला।',
  'Lab report details will be added when available.': 'जांच री जानकारी मिलते ई जोड़ांला।',
  'Delivery information will be shown with your order.': 'डिलिवरी री जानकारी थारे ऑर्डर में दिखसी।',
  'Customer reviews will appear here when available.': 'ग्राहकां री राय मिलते ई इठे दिखसी।',
  'Common questions': 'आम सवाल', 'Simple answers about prices, products, and custom puja kits.': 'भाव, सामान अर पूजा किट री सीधी बात।',
  'Get product updates': 'सामान री खबर पावो', 'Sign up to hear about new products and seasonal collections.': 'नवे सामान अर मौसम री खास चीजां री खबर पावो।',
  'Email address': 'ईमेल पतों', 'Enter your email': 'अपणो ईमेल लिखो',
  'Our product range': 'म्हारो सामान', 'Browse by category': 'किस्म सूं देखो', 'Find puja and wellness essentials': 'पूजा अर सेहत रो सामान देखो',
  'View products': 'सामान देखो', 'Build a kit that fits your needs': 'अपणी जरूरत री किट बनावो',
  'Make your puja kit your way:': 'अपणी पूजा किट खुद बनावो:', 'Choose your items and amounts.': 'सामान अर मात्रा चुनो।',
  'Choose the puja items and amounts you need. Leave out anything you already have at home, and see the price update as you make changes.': 'पूजा रो सामान अर मात्रा चुनो। घर में जो है, उणने छोड़ दो। बदलाव सूं भाव भी बदलसी।',
  'Your kit price updates as you change the items and amounts.': 'सामान अर मात्रा बदलो तो किट रो भाव बदलसी।',
  'Pick herbs, camphor, oils, wood, or brass items for your kit.': 'किट वास्ते जड़ी-बूटी, कपूर, तेल, लकड़ी अर पीतल रो सामान चुनो।',
  'Set amounts': 'मात्रा राखो', 'Choose how much of each item you need.': 'हर चीज री जरूरत जितणी मात्रा चुनो।',
  'Delivery to your home': 'घर पर डिलिवरी', 'Choose your kit and enter your delivery address at checkout.': 'किट चुनो अर ऑर्डर देतां बेर पतो लिखो।',
  'Choose a list suggested by puja experts. Already have some items? Lower their quantities. Need something else? Add it to your kit.': 'पूजा जाणकारां री सूची चुनो। घर में सामान है? मात्रा घटावो। और सामान चाहिजे? किट में जोड़ो।',
  'Puja expert suggestions': 'पूजा जाणकारां री सलाह', 'Loading your puja kit...': 'थारी पूजा किट खुलै है...',
  'Starting price': 'शुरू रो भाव', 'Puja essential': 'पूजा रो जरूरी सामान', Changed: 'बदलियो',
  'Not needed (already at home)': 'ना चाहिजे (घर में है)', 'Items and amounts you selected': 'थारो चुन्यो सामान अर मात्रा',
  'Kit starting price': 'किट रो शुरू भाव', Amount: 'मात्रा', Custom: 'अपणी पसंद',
  'Placing your order...': 'थारो ऑर्डर भेजै है...',
  'Items set to zero will not be packed. Remove anything you already have at home.': 'जिण चीज री मात्रा शून्य है, वो किट में ना आवे। घर में हो उणने छोड़ दो।',
  'Browse our products and add something you like.': 'सामान देखो अर पसंद आवे वो जोड़ो।', Unlocked: 'मिल गयो',
  'for free delivery': 'अर डिलिवरी मुफ्त पावो', each: 'हर चीज', Free: 'मुफ्त', 'Clear all items from cart': 'थैली रो सगळो सामान हटावो',
};

const gujaratiTranslations: Record<string, string> = {
  'Purity Is Our Pride • Fast Worldwide Handling • Traditional Sourcing': 'શુદ્ધતા અમારી ઓળખ • દુનિયાભરમાં ઝડપી ડિલિવરી • પરંપરાગત રીતે પસંદ કરેલી વસ્તુઓ',
  'Search by Formulation, Herb, Ritual...': 'ઉત્પાદન, જડીબુટ્ટી અથવા પૂજાની સામગ્રી શોધો...',
  Philosophy: 'અમારી વિચારધારા', Shop: 'ખરીદો', 'Custom Kit': 'તમારી પૂજા કિટ', Language: 'ભાષા પસંદ કરો',
  'Signed in as': 'લૉગ ઇન છો:', 'Account Settings': 'ખાતાની માહિતી', 'Order History': 'મારા ઑર્ડર',
  'Saved Addresses': 'મારા સરનામાં', 'Logged-in Devices': 'લૉગ ઇન કરેલાં ઉપકરણો', 'My Reviews': 'મારા અભિપ્રાયો',
  Notifications: 'સૂચનાઓ', 'Sign Out': 'લૉગ આઉટ', 'Dashboard Menu': 'ખાતા મેનૂ', 'Sign In': 'લૉગ ઇન',
  Home: 'હોમ', Kit: 'કિટ', Wishlist: 'મનપસંદ', Cart: 'થેલી', Account: 'ખાતું',
  'Build Custom Kit': 'તમારી પૂજા કિટ બનાવો', 'Explore Raw Herbs': 'જડીબુટ્ટીઓ જુઓ',
  'Build Your Puja Kit': 'તમારી પૂજા કિટ બનાવો', 'Choose a puja': 'પૂજા પસંદ કરો', 'Choose puja items': 'પૂજાની સામગ્રી પસંદ કરો',
  'Use suggested amounts': 'સૂચવેલી માત્રા રાખો', 'Suggested amount': 'સૂચવેલી માત્રા', 'Your kit': 'તમારી કિટ',
  'Estimated total': 'અંદાજિત કુલ', 'Place kit order': 'કિટનો ઑર્ડર આપો', 'Your kit is empty.': 'તમારી કિટ ખાલી છે.',
  'Your Cart': 'તમારી થેલી', 'Cart Summary': 'થેલીની વિગતો', 'Review your selected products before checkout.': 'ઑર્ડર આપતાં પહેલાં પસંદ કરેલી વસ્તુઓ તપાસો.',
  Piece: 'વસ્તુ', Pieces: 'વસ્તુઓ', 'Clear Cart': 'થેલી ખાલી કરો', 'Your cart is empty': 'તમારી થેલી ખાલી છે.',
  'Explore Collection': 'વસ્તુઓ જુઓ', 'Proceed to Checkout': 'ઑર્ડર આગળ વધારો', Checkout: 'ઑર્ડર કરો',
  Subtotal: 'ઉપકુલ', Delivery: 'ડિલિવરી', Total: 'કુલ', 'Free shipping': 'મફત ડિલિવરી',
  'Taxes included': 'ટૅક્સ સામેલ', 'Secure payment': 'સુરક્ષિત ચુકવણી', 'Careful packing and delivery': 'સુરક્ષિત પૅકિંગ અને ડિલિવરી',
  'Product name': 'ઉત્પાદનનું નામ', 'Health concern': 'આરોગ્યની સમસ્યા', Herb: 'જડીબુટ્ટી', Puja: 'પૂજા',
  'Sanskrit name': 'સંસ્કૃત નામ', 'Hindi name': 'હિન્દી નામ', 'English name': 'અંગ્રેજી નામ',
  'How do you keep prices fair?': 'તમે યોગ્ય ભાવ કેવી રીતે રાખો છો?',
  'We work with growers and local makers where possible, helping us offer good products at fair prices.': 'શક્ય હોય ત્યાં અમે ખેડૂતો અને સ્થાનિક કારીગરો પાસેથી સીધો માલ લઈએ છીએ, જેથી યોગ્ય ભાવ રાખી શકીએ.',
  'Can I choose what goes in my puja kit?': 'મારી પૂજા કિટમાં શું હશે તે હું પસંદ કરી શકું?',
  'Yes. Choose the items and amounts you need. Leave out anything you already have at home.': 'હા. જરૂરી વસ્તુઓ અને તેમનું પ્રમાણ પસંદ કરો. ઘરે પહેલેથી હોય તે વસ્તુઓ કાઢી નાખો.',
  'Where can I find certificates and customer reviews?': 'પ્રમાણપત્રો અને ગ્રાહકોના અભિપ્રાય ક્યાં મળશે?',
  'We will show product certificates and customer reviews here once they are available.': 'ઉત્પાદનનાં પ્રમાણપત્રો અને ગ્રાહકોના અભિપ્રાય ઉપલબ્ધ થશે ત્યારે અહીં બતાવીશું.',
  'Our products': 'અમારી વસ્તુઓ', 'Popular products': 'લોકપ્રિય વસ્તુઓ', All: 'બધું',
  'Loading products...': 'વસ્તુઓ લોડ થાય છે...', 'Products could not be loaded': 'વસ્તુઓ લોડ થઈ શકી નથી',
  'Please try again in a moment.': 'થોડી વાર પછી ફરી પ્રયાસ કરો.', 'No products found in this category.': 'આ પ્રકારની કોઈ વસ્તુ મળી નથી.',
  'Product image unavailable': 'વસ્તુનો ફોટો ઉપલબ્ધ નથી', 'Other products': 'બીજી વસ્તુઓ', Price: 'ભાવ', 'Add to cart': 'થેલીમાં ઉમેરો',
  'Made for everyone': 'બધા માટે', 'Easy to use for every family': 'દરેક પરિવાર માટે સરળ',
  'Find puja and wellness products with clear names, prices, and details.': 'પૂજા અને આરોગ્યની વસ્તુઓ સ્પષ્ટ નામ, ભાવ અને માહિતી સાથે જુઓ.',
  'For homes, puja, and everyday wellness': 'ઘર, પૂજા અને રોજિંદા આરોગ્ય માટે',
  'Families who perform puja at home': 'ઘરે પૂજા કરતા પરિવારો', 'Priests and puja guides': 'પૂજારી અને પૂજા માર્ગદર્શકો',
  'People who use Ayurvedic products': 'આયુર્વેદિક વસ્તુઓ વાપરતા લોકો', 'Older adults and spiritual learners': 'વડીલો અને આધ્યાત્મિક અભ્યાસીઓ',
  'Families looking for fair prices': 'યોગ્ય ભાવ શોધતા પરિવારો', 'Product checks': 'વસ્તુઓની તપાસ',
  'Clear product information': 'વસ્તુઓની સ્પષ્ટ માહિતી',
  'We only share details that have been checked. More information will be added when it is available.': 'તપાસેલી માહિતી જ આપીએ છીએ. વધુ માહિતી મળશે ત્યારે ઉમેરીશું.',
  'AYUSH licence': 'આયુષ લાઇસન્સ', 'FSSAI certificate': 'એફએસએસએઆઈ પ્રમાણપત્ર', 'Lab test reports': 'લૅબ તપાસના અહેવાલ',
  'Packing and delivery': 'પૅકિંગ અને ડિલિવરી', 'Certificate details will be added when available.': 'પ્રમાણપત્રની માહિતી મળશે ત્યારે ઉમેરીશું.',
  'Lab report details will be added when available.': 'લૅબ અહેવાલની માહિતી મળશે ત્યારે ઉમેરીશું.',
  'Delivery information will be shown with your order.': 'ડિલિવરીની માહિતી તમારા ઑર્ડરમાં દેખાશે.',
  'Customer reviews will appear here when available.': 'ગ્રાહકોના અભિપ્રાય મળશે ત્યારે અહીં દેખાશે.',
  'Common questions': 'સામાન્ય પ્રશ્નો', 'Simple answers about prices, products, and custom puja kits.': 'ભાવ, વસ્તુઓ અને પૂજા કિટ વિશે સરળ જવાબો.',
  'Get product updates': 'નવી વસ્તુઓની જાણકારી મેળવો', 'Sign up to hear about new products and seasonal collections.': 'નવી વસ્તુઓ અને મોસમી સંગ્રહની માહિતી મેળવો.',
  'Email address': 'ઇમેઇલ સરનામું', 'Enter your email': 'તમારો ઇમેઇલ લખો',
  'Our product range': 'અમારી વસ્તુઓ', 'Browse by category': 'પ્રકાર પ્રમાણે જુઓ', 'Find puja and wellness essentials': 'પૂજા અને આરોગ્યની વસ્તુઓ જુઓ',
  'View products': 'વસ્તુઓ જુઓ', 'Build a kit that fits your needs': 'તમારી જરૂરિયાત પ્રમાણે કિટ બનાવો',
  'Make your puja kit your way:': 'તમારી પૂજા કિટ જાતે બનાવો:', 'Choose your items and amounts.': 'વસ્તુઓ અને તેમનું પ્રમાણ પસંદ કરો.',
  'Choose the puja items and amounts you need. Leave out anything you already have at home, and see the price update as you make changes.': 'પૂજાની વસ્તુઓ અને તેમનું પ્રમાણ પસંદ કરો. ઘરે હોય તે વસ્તુઓ કાઢી નાખો. ફેરફાર સાથે ભાવ પણ બદલાશે.',
  'Your kit price updates as you change the items and amounts.': 'વસ્તુઓ કે પ્રમાણ બદલશો તો કિટનો ભાવ પણ બદલાશે.',
  'Pick herbs, camphor, oils, wood, or brass items for your kit.': 'કિટ માટે જડીબુટ્ટી, કપૂર, તેલ, લાકડું કે પિત્તળની વસ્તુઓ પસંદ કરો.',
  'Set amounts': 'પ્રમાણ નક્કી કરો', 'Choose how much of each item you need.': 'દરેક વસ્તુનું જરૂરી પ્રમાણ પસંદ કરો.',
  'Delivery to your home': 'ઘરે ડિલિવરી', 'Choose your kit and enter your delivery address at checkout.': 'કિટ પસંદ કરો અને ઑર્ડર આપતી વખતે સરનામું લખો.',
  'Puja expert suggestions': 'પૂજા જાણકારોની સલાહ', 'Loading your puja kit...': 'તમારી પૂજા કિટ લોડ થાય છે...',
  'Starting price': 'શરૂઆતનો ભાવ', 'Puja essential': 'પૂજાની જરૂરી વસ્તુ', Changed: 'બદલ્યું',
  'Not needed (already at home)': 'જરૂર નથી (ઘરે છે)', 'Items and amounts you selected': 'તમે પસંદ કરેલી વસ્તુઓ અને પ્રમાણ',
  'Kit starting price': 'કિટનો શરૂઆતનો ભાવ', Amount: 'પ્રમાણ', Custom: 'તમારી પસંદગી',
  'Placing your order...': 'તમારો ઑર્ડર મોકલાય છે...', 'Items set to zero will not be packed. Remove anything you already have at home.': 'પ્રમાણ શૂન્ય હશે તે વસ્તુ કિટમાં નહીં આવે. ઘરે હોય તે વસ્તુ કાઢી નાખો.',
  'Browse our products and add something you like.': 'વસ્તુઓ જુઓ અને ગમતી વસ્તુ ઉમેરો.', Unlocked: 'મળ્યું',
  'for free delivery': 'અને ડિલિવરી મફત મેળવો', each: 'દરેક', Free: 'મફત', 'Clear all items from cart': 'થેલીની બધી વસ્તુઓ કાઢો',
};

const sanskritTranslations: Record<string, string> = {
  'Purity Is Our Pride • Fast Worldwide Handling • Traditional Sourcing': 'शुद्धता अस्माकं गौरवम् • विश्वे शीघ्रं प्रेषणम् • परम्परया चयनितानि वस्तूनि',
  'Search by Formulation, Herb, Ritual...': 'उत्पादं, औषधिं वा पूजासामग्रीं अन्विष्यताम्...',
  Philosophy: 'अस्माकं विचारः', Shop: 'क्रेतुम्', 'Custom Kit': 'स्वकीयः पूजासञ्चयः', Language: 'भाषां चिनोतु',
  'Signed in as': 'प्रविष्टः:', 'Account Settings': 'खाताविवरणम्', 'Order History': 'मम आदेशाः',
  'Saved Addresses': 'मम पतनानि', 'Logged-in Devices': 'प्रविष्टानि उपकरणानि', 'My Reviews': 'मम अभिप्रायाः',
  Notifications: 'सूचनाः', 'Sign Out': 'निर्गच्छतु', 'Dashboard Menu': 'खातासूची', 'Sign In': 'प्रविशतु',
  Home: 'गृहम्', Kit: 'सञ्चयः', Wishlist: 'प्रियवस्तूनि', Cart: 'पेटिका', Account: 'खातम्',
  'Build Custom Kit': 'स्वकीयां पूजाकिटं रचयतु', 'Explore Raw Herbs': 'औषधिवनस्पतीः पश्यतु',
  'Build Your Puja Kit': 'स्वकीयां पूजाकिटं रचयतु', 'Choose a puja': 'पूजां चिनोतु', 'Choose puja items': 'पूजासामग्रीं चिनोतु',
  'Use suggested amounts': 'सूचितं परिमाणं स्थापयतु', 'Suggested amount': 'सूचितं परिमाणम्', 'Your kit': 'भवतः सञ्चयः',
  'Estimated total': 'अनुमानितं कुलम्', 'Place kit order': 'सञ्चयस्य आदेशं ददातु', 'Your kit is empty.': 'भवतः सञ्चयः रिक्तः अस्ति।',
  'Your Cart': 'भवतः पेटिका', 'Cart Summary': 'पेटिकायाः विवरणम्', 'Review your selected products before checkout.': 'आदेशात् पूर्वं चयनितानि वस्तूनि पश्यतु।',
  Piece: 'वस्तु', Pieces: 'वस्तूनि', 'Clear Cart': 'पेटिकां रिक्तां करोतु', 'Your cart is empty': 'भवतः पेटिका रिक्ता अस्ति।',
  'Explore Collection': 'वस्तूनि पश्यतु', 'Proceed to Checkout': 'आदेशं अग्रे नयतु', Checkout: 'आदेशं ददातु',
  Subtotal: 'उपयोगः', Delivery: 'प्रेषणम्', Total: 'कुलम्', 'Free shipping': 'निःशुल्कं प्रेषणम्',
  'Taxes included': 'कराः अन्तर्भूताः', 'Secure payment': 'सुरक्षितं भुगतानम्', 'Careful packing and delivery': 'सुरक्षितं वेष्टनं प्रेषणं च',
  'Product name': 'उत्पादनस्य नाम', 'Health concern': 'स्वास्थ्यसमस्या', Herb: 'औषधिवनस्पतिः', Puja: 'पूजा',
  'Sanskrit name': 'संस्कृतनाम', 'Hindi name': 'हिन्दीनाम', 'English name': 'आङ्ग्लनाम',
  'How do you keep prices fair?': 'भवान् उचितमूल्यानि कथं स्थापयति?',
  'We work with growers and local makers where possible, helping us offer good products at fair prices.': 'यत्र शक्यते तत्र वयं कृषकैः स्थानीयशिल्पिभिः च सह कार्यं कुर्मः, येन वस्तूनि उचितमूल्येन दातुं शक्नुमः।',
  'Can I choose what goes in my puja kit?': 'मम पूजासञ्चये कानि वस्तूनि स्युः इति अहं चिनोतुं शक्नोमि किम्?',
  'Yes. Choose the items and amounts you need. Leave out anything you already have at home.': 'आम्। आवश्यकानि वस्तूनि तेषां परिमाणं च चिनोतु। गृहे विद्यमानानि वस्तूनि त्यजतु।',
  'Where can I find certificates and customer reviews?': 'प्रमाणपत्राणि ग्राहकमतानि च कुत्र प्राप्स्यामि?',
  'We will show product certificates and customer reviews here once they are available.': 'उत्पादनप्रमाणपत्राणि ग्राहकमतानि च लब्धानि चेत् अत्र दर्शयिष्यामः।',
  'Our products': 'अस्माकं वस्तूनि', 'Popular products': 'लोकप्रियवस्तूनि', All: 'सर्वाणि',
  'Loading products...': 'वस्तूनि सज्जीकृतानि भवन्ति...', 'Products could not be loaded': 'वस्तूनि न प्रदर्शितानि',
  'Please try again in a moment.': 'कृपया किञ्चित्कालानन्तरं पुनः प्रयतताम्।', 'No products found in this category.': 'अस्मिन् वर्गे वस्तूनि न प्राप्तानि।',
  'Product image unavailable': 'वस्तुचित्रं न उपलब्धम्', 'Other products': 'अन्यानि वस्तूनि', Price: 'मूल्यम्', 'Add to cart': 'पेटिकायां योजयतु',
  'Made for everyone': 'सर्वेषां कृते', 'Easy to use for every family': 'प्रत्येककुटुम्बस्य कृते सरलम्',
  'Find puja and wellness products with clear names, prices, and details.': 'पूजायाः स्वास्थ्यस्य च वस्तूनि स्पष्टनामभिः मूल्यैः विवरणैः च पश्यतु।',
  'For homes, puja, and everyday wellness': 'गृहपूजायै दैनिकस्वास्थ्याय च',
  'Families who perform puja at home': 'गृहे पूजां कुर्वन्तः कुटुम्बाः', 'Priests and puja guides': 'पुरोहिताः पूजामार्गदर्शकाश्च',
  'People who use Ayurvedic products': 'आयुर्वेदिकवस्तूनि उपयुञ्जानाः जनाः', 'Older adults and spiritual learners': 'वृद्धाः आध्यात्मिकविद्यार्थिनश्च',
  'Families looking for fair prices': 'उचितमूल्यानि अन्विष्यमाणाः कुटुम्बाः', 'Product checks': 'वस्तुपरीक्षणम्',
  'Clear product information': 'वस्तूनां स्पष्टविवरणम्',
  'We only share details that have been checked. More information will be added when it is available.': 'परीक्षितं विवरणमेव वयं दद्मः। अन्यद्विवरणं लब्धं चेत् योजयिष्यामः।',
  'AYUSH licence': 'आयुष् अनुमतिपत्रम्', 'FSSAI certificate': 'एफ्.एस्.एस्.ए.आइ प्रमाणपत्रम्', 'Lab test reports': 'प्रयोगशालापरीक्षणविवरणम्',
  'Packing and delivery': 'आवरणं प्रेषणं च', 'Certificate details will be added when available.': 'प्रमाणपत्रविवरणं लब्धं चेत् योजयिष्यामः।',
  'Lab report details will be added when available.': 'प्रयोगशालाविवरणं लब्धं चेत् योजयिष्यामः।',
  'Delivery information will be shown with your order.': 'प्रेषणविवरणं भवतः आदेशे दर्शयिष्यते।',
  'Customer reviews will appear here when available.': 'ग्राहकमतानि लब्धानि चेत् अत्र दर्शयिष्यन्ते।',
  'Common questions': 'सामान्यप्रश्नाः', 'Simple answers about prices, products, and custom puja kits.': 'मूल्यानां वस्तूनां स्वकीयपूजासञ्चयानां च सरलानि उत्तराणि।',
  'Get product updates': 'नवीनवस्तुविवरणं प्राप्नोतु', 'Sign up to hear about new products and seasonal collections.': 'नवीनवस्तूनां ऋतुसङ्ग्रहस्य च विवरणं प्राप्नोतु।',
  'Email address': 'ईमेलपत्रसङ्केतः', 'Enter your email': 'ईमेलपत्रसङ्केतं लिखतु',
  'Our product range': 'अस्माकं वस्तूनि', 'Browse by category': 'वर्गेण पश्यतु', 'Find puja and wellness essentials': 'पूजायाः स्वास्थ्यस्य च वस्तूनि पश्यतु',
  'View products': 'वस्तूनि पश्यतु', 'Build a kit that fits your needs': 'आवश्यकतानुसारं सञ्चयं रचयतु',
  'Make your puja kit your way:': 'स्वकीयपूजासञ्चयं रचयतु:', 'Choose your items and amounts.': 'वस्तूनि परिमाणानि च चिनोतु।',
  'Choose the puja items and amounts you need. Leave out anything you already have at home, and see the price update as you make changes.': 'पूजावस्तूनि तेषां परिमाणं च चिनोतु। गृहे विद्यमानानि वस्तूनि त्यजतु। परिवर्तनेन मूल्यं अपि परिवर्तते।',
  'Your kit price updates as you change the items and amounts.': 'वस्तुपरिमाणपरिवर्तनेन सञ्चयमूल्यमपि परिवर्तते।',
  'Pick herbs, camphor, oils, wood, or brass items for your kit.': 'सञ्चयाय औषधिवनस्पतीः कर्पूरं तैलं काष्ठं पीतलवस्तूनि वा चिनोतु।',
  'Set amounts': 'परिमाणं चिनोतु', 'Choose how much of each item you need.': 'प्रत्येकवस्तुनः आवश्यकं परिमाणं चिनोतु।',
  'Delivery to your home': 'गृहे प्रेषणम्', 'Choose your kit and enter your delivery address at checkout.': 'सञ्चयं चिनोतु आदेशसमये च पतनं लिखतु।',
  'Puja expert suggestions': 'पूजाविदुषां सुझावः', 'Loading your puja kit...': 'पूजासञ्चयः सज्जीक्रियते...',
  'Starting price': 'आरम्भिकमूल्यम्', 'Puja essential': 'पूजायाः आवश्यकवस्तु', Changed: 'परिवर्तितम्',
  'Not needed (already at home)': 'आवश्यकं न (गृहे अस्ति)', 'Items and amounts you selected': 'चयनितानि वस्तूनि परिमाणानि च',
  'Kit starting price': 'सञ्चयस्य आरम्भिकमूल्यम्', Amount: 'परिमाणम्', Custom: 'स्वेच्छया',
  'Placing your order...': 'आदेशः प्रेष्यते...', 'Items set to zero will not be packed. Remove anything you already have at home.': 'शून्यपरिमाणवस्तु सञ्चये न स्थाप्यते। गृहे विद्यमानं वस्तु त्यजतु।',
  'Browse our products and add something you like.': 'वस्तूनि पश्यतु रोचमानं वस्तु च योजयतु।', Unlocked: 'प्राप्तम्',
  'for free delivery': 'निःशुल्कप्रेषणाय', each: 'प्रत्येकम्', Free: 'निःशुल्कम्', 'Clear all items from cart': 'पेटिकायाः सर्ववस्तूनि निष्कासयतु',
};

const translations: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  hi: hindiTranslations,
  mr: marathiTranslations,
  mwr: marwariTranslations,
  gu: gujaratiTranslations,
  sa: sanskritTranslations,
};

const checkoutTranslations: Record<Exclude<Language, 'en'>, Record<string, string>> = {
  hi: {
    'Preparing checkout...': 'चेकआउट तैयार हो रहा है...', 'Back to Cart': 'टोकरी पर वापस जाएँ',
    'Delivery address': 'डिलीवरी का पता', 'Add new': 'नया जोड़ें',
    'No delivery addresses found. Add one to continue.': 'डिलीवरी का पता नहीं मिला। आगे बढ़ने के लिए पता जोड़ें।',
    'Add delivery address': 'डिलीवरी का पता जोड़ें', Default: 'मुख्य पता',
    'Selected address': 'चुना हुआ पता', 'Select address': 'पता चुनें', 'Payment method': 'भुगतान का तरीका',
    'Online payment': 'ऑनलाइन भुगतान', 'UPI, cards, net banking, and wallets': 'UPI, कार्ड, नेट बैंकिंग और वॉलेट',
    'Cash on delivery': 'सामान मिलने पर भुगतान', 'Pay when your order arrives.': 'ऑर्डर मिलने पर भुगतान करें।',
    'Order items': 'ऑर्डर का सामान', 'Edit items': 'सामान बदलें', 'Order summary': 'ऑर्डर का सार',
    'Order total': 'ऑर्डर की कुल कीमत', 'Delivering to': 'यहाँ भेजें', Shipping: 'डिलीवरी शुल्क',
    'Place order': 'ऑर्डर दें', 'Delivery updates after dispatch': 'भेजे जाने के बाद डिलीवरी की जानकारी मिलेगी',
    'Add an address for future deliveries.': 'आगे की डिलीवरी के लिए पता जोड़ें।', 'Full name': 'पूरा नाम',
    'Phone number': 'फ़ोन नंबर', 'Address line 1': 'पता', 'House or flat, building, street': 'घर या फ़्लैट, इमारत, सड़क',
    'Address line 2 (optional)': 'पते की दूसरी पंक्ति (ज़रूरी नहीं)', 'Landmark or area': 'नज़दीकी जगह या इलाका',
    City: 'शहर', State: 'राज्य', 'Postal code': 'पिन कोड', Country: 'देश',
    'Use as my default address': 'इसे मेरा मुख्य पता रखें', Cancel: 'रद्द करें', 'Save address': 'पता सेव करें',
    'Loading order details...': 'ऑर्डर की जानकारी खुल रही है...', 'Checking your order...': 'आपका ऑर्डर जाँचा जा रहा है...',
    'Order not found': 'ऑर्डर नहीं मिला', 'We could not find this order. Check the order link and try again.': 'यह ऑर्डर नहीं मिला। लिंक जाँचकर फिर कोशिश करें।',
    'Order confirmed': 'ऑर्डर पक्का हो गया', 'Thank you for your order': 'ऑर्डर करने के लिए धन्यवाद',
    'Your order number': 'आपका ऑर्डर नंबर', 'was placed on': 'इस तारीख को दिया गया:',
    'Estimated delivery: 2 - 4 business days': 'डिलीवरी में लगभग 2 से 4 कामकाजी दिन लगेंगे',
    Customer: 'ग्राहक', 'Payment details': 'भुगतान की जानकारी', Status: 'स्थिति',
    'Print receipt': 'रसीद प्रिंट करें', Quantity: 'मात्रा', 'Track order status': 'ऑर्डर की स्थिति देखें',
    'Continue shopping': 'खरीदारी जारी रखें',
    'Preparing your kit order...': 'आपकी किट का ऑर्डर तैयार हो रहा है...', 'No puja kit selected': 'कोई पूजा किट नहीं चुनी गई',
    'Choose your puja items before placing the order.': 'ऑर्डर देने से पहले पूजा का सामान चुनें।', 'Open kit builder': 'किट बनाएँ',
    'Back to kit builder': 'किट बनाने पर वापस जाएँ', 'Your kit items': 'आपकी किट का सामान', 'Edit kit': 'किट बदलें',
    'Kit price and packing': 'किट की कीमत और पैकिंग', Size: 'आकार', 'Kit base price': 'किट की शुरुआती कीमत',
    'Items total': 'सामान की कीमत', 'Delivery takes 3 to 5 business days': 'डिलीवरी में 3 से 5 कामकाजी दिन लगेंगे',
    'Packed with care in Shri Vishwanath packaging': 'श्री विश्वनाथ की पैकिंग में ध्यान से पैक किया जाएगा',
    'Your puja kit is being prepared': 'आपकी पूजा किट तैयार हो रही है', 'Estimated delivery: 1 - 3 business days': 'डिलीवरी में लगभग 1 से 3 कामकाजी दिन लगेंगे',
    'Kit status': 'किट की स्थिति', Payment: 'भुगतान', 'Total paid': 'कुल भुगतान', 'Build another kit': 'एक और किट बनाएँ',
    Description: 'विवरण', 'Product details': 'उत्पाद की जानकारी', Reviews: 'समीक्षाएँ',
    'No extra product details are available.': 'उत्पाद की अतिरिक्त जानकारी उपलब्ध नहीं है।',
    'Product information': 'उत्पाद की जानकारी', 'We check product details and share clear information before you buy.': 'हम उत्पाद की जानकारी जाँचकर खरीदने से पहले साफ़ जानकारी देते हैं।',
    Source: 'स्रोत', 'Product details checked': 'उत्पाद की जानकारी जाँची गई',
    Included: 'शामिल', 'Included in kit price': 'किट की कीमत में शामिल', 'Product details unavailable': 'उत्पाद की जानकारी उपलब्ध नहीं है',
    'First item and delivery are included in the kit price. Extra quantities are charged.': 'पहला सामान और डिलीवरी किट की कीमत में शामिल हैं। अतिरिक्त मात्रा का शुल्क लगेगा।',
  },
  mr: {
    'Preparing checkout...': 'ऑर्डरची तयारी सुरू आहे...', 'Back to Cart': 'पिशवीत परत जा',
    'Delivery address': 'डिलिव्हरीचा पत्ता', 'Add new': 'नवीन जोडा',
    'No delivery addresses found. Add one to continue.': 'डिलिव्हरीचा पत्ता नाही. पुढे जाण्यासाठी पत्ता जोडा.',
    'Add delivery address': 'डिलिव्हरीचा पत्ता जोडा', Default: 'मुख्य पत्ता',
    'Selected address': 'निवडलेला पत्ता', 'Select address': 'पत्ता निवडा', 'Payment method': 'पेमेंटची पद्धत',
    'Online payment': 'ऑनलाइन पेमेंट', 'UPI, cards, net banking, and wallets': 'UPI, कार्ड, नेट बँकिंग आणि वॉलेट',
    'Cash on delivery': 'वस्तू मिळाल्यावर पैसे द्या', 'Pay when your order arrives.': 'ऑर्डर मिळाल्यावर पैसे द्या.',
    'Order items': 'ऑर्डरमधील वस्तू', 'Edit items': 'वस्तू बदला', 'Order summary': 'ऑर्डरचा तपशील',
    'Order total': 'ऑर्डरची एकूण किंमत', 'Delivering to': 'येथे पाठवत आहोत', Shipping: 'डिलिव्हरी शुल्क',
    'Place order': 'ऑर्डर द्या', 'Delivery updates after dispatch': 'ऑर्डर पाठवल्यावर डिलिव्हरीची माहिती मिळेल',
    'Add an address for future deliveries.': 'पुढील डिलिव्हरीसाठी पत्ता जोडा.', 'Full name': 'पूर्ण नाव',
    'Phone number': 'फोन नंबर', 'Address line 1': 'पत्ता', 'House or flat, building, street': 'घर किंवा फ्लॅट, इमारत, रस्ता',
    'Address line 2 (optional)': 'पत्त्याची दुसरी ओळ (ऐच्छिक)', 'Landmark or area': 'जवळची खूण किंवा परिसर',
    City: 'शहर', State: 'राज्य', 'Postal code': 'पिन कोड', Country: 'देश',
    'Use as my default address': 'हा माझा मुख्य पत्ता ठेवा', Cancel: 'रद्द करा', 'Save address': 'पत्ता जतन करा',
    'Loading order details...': 'ऑर्डरची माहिती लोड होत आहे...', 'Checking your order...': 'तुमची ऑर्डर तपासत आहोत...',
    'Order not found': 'ऑर्डर सापडली नाही', 'We could not find this order. Check the order link and try again.': 'ही ऑर्डर सापडली नाही. लिंक तपासून पुन्हा प्रयत्न करा.',
    'Order confirmed': 'ऑर्डर निश्चित झाली', 'Thank you for your order': 'ऑर्डर दिल्याबद्दल धन्यवाद',
    'Your order number': 'तुमचा ऑर्डर क्रमांक', 'was placed on': 'या दिवशी दिली:',
    'Estimated delivery: 2 - 4 business days': 'डिलिव्हरीसाठी साधारण २ ते ४ कामकाजाचे दिवस लागतील',
    Customer: 'ग्राहक', 'Payment details': 'पेमेंटची माहिती', Status: 'स्थिती',
    'Print receipt': 'पावती छापा', Quantity: 'प्रमाण', 'Track order status': 'ऑर्डरची स्थिती पाहा',
    'Continue shopping': 'खरेदी सुरू ठेवा',
    'Preparing your kit order...': 'तुमच्या किटची ऑर्डर तयार होत आहे...', 'No puja kit selected': 'पूजा किट निवडलेली नाही',
    'Choose your puja items before placing the order.': 'ऑर्डर देण्यापूर्वी पूजेच्या वस्तू निवडा.', 'Open kit builder': 'किट तयार करा',
    'Back to kit builder': 'किट तयार करण्याकडे परत जा', 'Your kit items': 'तुमच्या किटमधील वस्तू', 'Edit kit': 'किट बदला',
    'Kit price and packing': 'किटची किंमत आणि पॅकिंग', Size: 'आकार', 'Kit base price': 'किटची सुरुवातीची किंमत',
    'Items total': 'वस्तूंची एकूण किंमत', 'Delivery takes 3 to 5 business days': 'डिलिव्हरीसाठी ३ ते ५ कामकाजाचे दिवस लागतील',
    'Packed with care in Shri Vishwanath packaging': 'श्री विश्वनाथच्या पॅकिंगमध्ये काळजीपूर्वक पॅक केले जाईल',
    'Your puja kit is being prepared': 'तुमची पूजा किट तयार होत आहे', 'Estimated delivery: 1 - 3 business days': 'डिलिव्हरीसाठी साधारण १ ते ३ कामकाजाचे दिवस लागतील',
    'Kit status': 'किटची स्थिती', Payment: 'पेमेंट', 'Total paid': 'एकूण भरले', 'Build another kit': 'आणखी एक किट तयार करा',
    Description: 'वर्णन', 'Product details': 'उत्पादनाची माहिती', Reviews: 'मते',
    'No extra product details are available.': 'उत्पादनाची अतिरिक्त माहिती उपलब्ध नाही.',
    'Product information': 'उत्पादनाची माहिती', 'We check product details and share clear information before you buy.': 'आम्ही उत्पादनाची माहिती तपासून खरेदीपूर्वी स्पष्ट माहिती देतो.',
    Source: 'स्रोत', 'Product details checked': 'उत्पादनाची माहिती तपासली',
    Included: 'समाविष्ट', 'Included in kit price': 'किटच्या किमतीत समाविष्ट', 'Product details unavailable': 'उत्पादनाची माहिती उपलब्ध नाही',
    'First item and delivery are included in the kit price. Extra quantities are charged.': 'पहिली वस्तू आणि डिलिव्हरी किटच्या किमतीत समाविष्ट आहे. जास्त प्रमाणासाठी पैसे लागतील.',
  },
  mwr: {
    'Preparing checkout...': 'ऑर्डर री तैयारी होवै है...', 'Back to Cart': 'थैली में लौटो',
    'Delivery address': 'डिलिवरी रो पतो', 'Add new': 'नवो जोड़ो',
    'No delivery addresses found. Add one to continue.': 'डिलिवरी रो पतो ना मिल्यो। आगै बढ़बा वास्ते पतो जोड़ो।',
    'Add delivery address': 'डिलिवरी रो पतो जोड़ो', Default: 'मुख्य पतो',
    'Selected address': 'चुन्यो पतो', 'Select address': 'पतो चुनो', 'Payment method': 'पैसा देबा रो तरीका',
    'Online payment': 'ऑनलाइन पेमेंट', 'UPI, cards, net banking, and wallets': 'UPI, कार्ड, नेट बैंकिंग अर वॉलेट',
    'Cash on delivery': 'सामान मिलै तब पैसा दो', 'Pay when your order arrives.': 'ऑर्डर मिलै तब पैसा दो।',
    'Order items': 'ऑर्डर रो सामान', 'Edit items': 'सामान बदलो', 'Order summary': 'ऑर्डर रो ब्यौरो',
    'Order total': 'ऑर्डर रो कुल भाव', 'Delivering to': 'इठे भेजै है', Shipping: 'डिलिवरी रो भाव',
    'Place order': 'ऑर्डर करो', 'Delivery updates after dispatch': 'सामान भेज्या पाछै डिलिवरी री खबर मिलसी',
    'Add an address for future deliveries.': 'आगै डिलिवरी वास्ते पतो जोड़ो।', 'Full name': 'पूरो नाम',
    'Phone number': 'फोन नंबर', 'Address line 1': 'पतो', 'House or flat, building, street': 'घर या फ्लैट, इमारत, गली',
    'Address line 2 (optional)': 'पते री दूसरी लाइन (जरूरी ना)', 'Landmark or area': 'नजदीक री जगह या इलाको',
    City: 'शहर', State: 'राज', 'Postal code': 'पिन कोड', Country: 'देश',
    'Use as my default address': 'ई म्हारो मुख्य पतो राखो', Cancel: 'रद्द करो', 'Save address': 'पतो सहेजो',
    'Loading order details...': 'ऑर्डर री जानकारी खुलै है...', 'Checking your order...': 'थारो ऑर्डर जांचै है...',
    'Order not found': 'ऑर्डर ना मिल्यो', 'We could not find this order. Check the order link and try again.': 'ई ऑर्डर ना मिल्यो। लिंक जांचो अर फेर कोशिश करो।',
    'Order confirmed': 'ऑर्डर पक्को', 'Thank you for your order': 'ऑर्डर वास्ते धन्यवाद',
    'Your order number': 'थारो ऑर्डर नंबर', 'was placed on': 'ई तारीख ने दियो:',
    'Estimated delivery: 2 - 4 business days': 'डिलिवरी में २ सूं ४ कामकाज रा दिन लागसी',
    Customer: 'ग्राहक', 'Payment details': 'पेमेंट री जानकारी', Status: 'हालत',
    'Print receipt': 'रसीद छापो', Quantity: 'मात्रा', 'Track order status': 'ऑर्डर री हालत देखो',
    'Continue shopping': 'खरीद चालू राखो',
    'Preparing your kit order...': 'थारी किट रो ऑर्डर तैयार होवै है...', 'No puja kit selected': 'पूजा किट ना चुनी',
    'Choose your puja items before placing the order.': 'ऑर्डर करबा सूं पैली पूजा रो सामान चुनो।', 'Open kit builder': 'किट बनावो',
    'Back to kit builder': 'किट बनावण में लौटो', 'Your kit items': 'थारी किट रो सामान', 'Edit kit': 'किट बदलो',
    'Kit price and packing': 'किट रो भाव अर पैकिंग', Size: 'नाप', 'Kit base price': 'किट रो शुरू भाव',
    'Items total': 'सामान रो कुल भाव', 'Delivery takes 3 to 5 business days': 'डिलिवरी में ३ सूं ५ कामकाज रा दिन लागसी',
    'Packed with care in Shri Vishwanath packaging': 'श्री विश्वनाथ री पैकिंग में ध्यान सूं पैक होसी',
    'Your puja kit is being prepared': 'थारी पूजा किट तैयार होवै है', 'Estimated delivery: 1 - 3 business days': 'डिलिवरी में १ सूं ३ दिन लागसी',
    'Kit status': 'किट री हालत', Payment: 'पेमेंट', 'Total paid': 'कुल दियो', 'Build another kit': 'दूजी किट बनावो',
    Description: 'विवरण', 'Product details': 'सामान री जानकारी', Reviews: 'राय',
    'No extra product details are available.': 'सामान री और जानकारी ना है।',
    'Product information': 'सामान री जानकारी', 'We check product details and share clear information before you buy.': 'खरीद सूं पैली सामान जांचां अर साफ जानकारी देवां।',
    Source: 'स्रोत', 'Product details checked': 'सामान री जानकारी जांची',
    Included: 'शामिल', 'Included in kit price': 'किट रे भाव में शामिल', 'Product details unavailable': 'सामान री जानकारी ना है',
    'First item and delivery are included in the kit price. Extra quantities are charged.': 'पैली चीज अर डिलिवरी किट रे भाव में शामिल है। ज्यादा मात्रा रो भाव अलग लागसी।',
  },
  gu: {
    'Preparing checkout...': 'ઑર્ડર તૈયાર થાય છે...', 'Back to Cart': 'થેલીમાં પાછા જાઓ',
    'Delivery address': 'ડિલિવરીનું સરનામું', 'Add new': 'નવું ઉમેરો',
    'No delivery addresses found. Add one to continue.': 'ડિલિવરીનું સરનામું મળ્યું નથી. આગળ વધવા માટે સરનામું ઉમેરો.',
    'Add delivery address': 'ડિલિવરીનું સરનામું ઉમેરો', Default: 'મુખ્ય સરનામું',
    'Selected address': 'પસંદ કરેલું સરનામું', 'Select address': 'સરનામું પસંદ કરો', 'Payment method': 'ચુકવણીની રીત',
    'Online payment': 'ઑનલાઇન ચુકવણી', 'UPI, cards, net banking, and wallets': 'UPI, કાર્ડ, નેટ બેન્કિંગ અને વૉલેટ',
    'Cash on delivery': 'વસ્તુ મળે ત્યારે ચૂકવો', 'Pay when your order arrives.': 'ઑર્ડર મળે ત્યારે ચુકવણી કરો.',
    'Order items': 'ઑર્ડરની વસ્તુઓ', 'Edit items': 'વસ્તુઓ બદલો', 'Order summary': 'ઑર્ડરની વિગતો',
    'Order total': 'ઑર્ડરની કુલ રકમ', 'Delivering to': 'અહીં મોકલવાનું છે', Shipping: 'ડિલિવરી ખર્ચ',
    'Place order': 'ઑર્ડર આપો', 'Delivery updates after dispatch': 'વસ્તુ મોકલ્યા પછી ડિલિવરીની માહિતી મળશે',
    'Add an address for future deliveries.': 'આગળની ડિલિવરી માટે સરનામું ઉમેરો.', 'Full name': 'પૂરું નામ',
    'Phone number': 'ફોન નંબર', 'Address line 1': 'સરનામું', 'House or flat, building, street': 'ઘર કે ફ્લૅટ, ઇમારત, શેરી',
    'Address line 2 (optional)': 'સરનામાની બીજી લાઇન (વૈકલ્પિક)', 'Landmark or area': 'નજીકની જગ્યા કે વિસ્તાર',
    City: 'શહેર', State: 'રાજ્ય', 'Postal code': 'પિન કોડ', Country: 'દેશ',
    'Use as my default address': 'આને મારું મુખ્ય સરનામું રાખો', Cancel: 'રદ કરો', 'Save address': 'સરનામું સાચવો',
    'Loading order details...': 'ઑર્ડરની માહિતી લોડ થાય છે...', 'Checking your order...': 'તમારો ઑર્ડર તપાસીએ છીએ...',
    'Order not found': 'ઑર્ડર મળ્યો નથી', 'We could not find this order. Check the order link and try again.': 'આ ઑર્ડર મળ્યો નથી. લિંક તપાસીને ફરી પ્રયાસ કરો.',
    'Order confirmed': 'ઑર્ડર નક્કી થયો', 'Thank you for your order': 'ઑર્ડર આપવા બદલ આભાર',
    'Your order number': 'તમારો ઑર્ડર નંબર', 'was placed on': 'આ તારીખે આપ્યો:',
    'Estimated delivery: 2 - 4 business days': 'ડિલિવરીમાં આશરે ૨ થી ૪ કામકાજના દિવસ લાગશે',
    Customer: 'ગ્રાહક', 'Payment details': 'ચુકવણીની માહિતી', Status: 'સ્થિતિ',
    'Print receipt': 'રસીદ છાપો', Quantity: 'જથ્થો', 'Track order status': 'ઑર્ડરની સ્થિતિ જુઓ',
    'Continue shopping': 'ખરીદી ચાલુ રાખો',
    'Preparing your kit order...': 'તમારી કિટનો ઑર્ડર તૈયાર થાય છે...', 'No puja kit selected': 'પૂજા કિટ પસંદ કરી નથી',
    'Choose your puja items before placing the order.': 'ઑર્ડર આપતાં પહેલાં પૂજાની વસ્તુઓ પસંદ કરો.', 'Open kit builder': 'કિટ બનાવો',
    'Back to kit builder': 'કિટ બનાવવામાં પાછા જાઓ', 'Your kit items': 'તમારી કિટની વસ્તુઓ', 'Edit kit': 'કિટ બદલો',
    'Kit price and packing': 'કિટનો ભાવ અને પૅકિંગ', Size: 'માપ', 'Kit base price': 'કિટનો શરૂઆતનો ભાવ',
    'Items total': 'વસ્તુઓનો કુલ ભાવ', 'Delivery takes 3 to 5 business days': 'ડિલિવરીમાં ૩ થી ૫ કામકાજના દિવસ લાગશે',
    'Packed with care in Shri Vishwanath packaging': 'શ્રી વિશ્વનાથના પૅકિંગમાં કાળજીથી પૅક થશે',
    'Your puja kit is being prepared': 'તમારી પૂજા કિટ તૈયાર થાય છે', 'Estimated delivery: 1 - 3 business days': 'ડિલિવરીમાં અંદાજે ૧ થી ૩ કામકાજના દિવસ લાગશે',
    'Kit status': 'કિટની સ્થિતિ', Payment: 'ચુકવણી', 'Total paid': 'કુલ ચૂકવ્યું', 'Build another kit': 'બીજી કિટ બનાવો',
    Description: 'વર્ણન', 'Product details': 'વસ્તુની માહિતી', Reviews: 'અભિપ્રાય',
    'No extra product details are available.': 'વસ્તુની વધુ માહિતી ઉપલબ્ધ નથી.',
    'Product information': 'વસ્તુની માહિતી', 'We check product details and share clear information before you buy.': 'ખરીદતાં પહેલાં અમે વસ્તુની માહિતી તપાસીને સ્પષ્ટ માહિતી આપીએ છીએ.',
    Source: 'સ્રોત', 'Product details checked': 'વસ્તુની માહિતી તપાસેલી છે',
    Included: 'સામેલ', 'Included in kit price': 'કિટના ભાવમાં સામેલ', 'Product details unavailable': 'વસ્તુની માહિતી ઉપલબ્ધ નથી',
    'First item and delivery are included in the kit price. Extra quantities are charged.': 'પહેલી વસ્તુ અને ડિલિવરી કિટના ભાવમાં સામેલ છે. વધારાના જથ્થાનો ખર્ચ લાગશે.',
  },
  sa: {
    'Preparing checkout...': 'आदेशः सज्जीक्रियते...', 'Back to Cart': 'पेटिकां प्रतिगच्छतु',
    'Delivery address': 'प्रेषणस्य पतनम्', 'Add new': 'नूतनं योजयतु',
    'No delivery addresses found. Add one to continue.': 'प्रेषणपतनं न प्राप्तम्। अग्रे गन्तुं पतनं योजयतु।',
    'Add delivery address': 'प्रेषणपतनं योजयतु', Default: 'मुख्यपतनम्',
    'Selected address': 'चयनितं पतनम्', 'Select address': 'पतनं चिनोतु', 'Payment method': 'भुगतानविधिः',
    'Online payment': 'अन्तर्जालभुगतानम्', 'UPI, cards, net banking, and wallets': 'UPI, कार्ड्, नेट्-बैंकिङ्ग्, वॉलेट् च',
    'Cash on delivery': 'वस्तुप्राप्तौ भुगतानम्', 'Pay when your order arrives.': 'आदेशप्राप्तौ भुगतानं करोतु।',
    'Order items': 'आदेशस्य वस्तूनि', 'Edit items': 'वस्तूनि परिवर्तयतु', 'Order summary': 'आदेशविवरणम्',
    'Order total': 'आदेशस्य कुलमूल्यम्', 'Delivering to': 'अत्र प्रेष्यते', Shipping: 'प्रेषणशुल्कम्',
    'Place order': 'आदेशं ददातु', 'Delivery updates after dispatch': 'प्रेषणानन्तरं सूचना प्राप्स्यते',
    'Add an address for future deliveries.': 'भविष्यत्प्रेषणाय पतनं योजयतु।', 'Full name': 'पूर्णं नाम',
    'Phone number': 'दूरभाषसङ्ख्या', 'Address line 1': 'पतनम्', 'House or flat, building, street': 'गृहं, भवनं, मार्गः',
    'Address line 2 (optional)': 'पतनस्य द्वितीयपङ्क्तिः (वैकल्पिकी)', 'Landmark or area': 'परिचितस्थानं क्षेत्रं वा',
    City: 'नगरम्', State: 'राज्यम्', 'Postal code': 'पिनसङ्केतः', Country: 'देशः',
    'Use as my default address': 'एतत् मुख्यपतनं करोतु', Cancel: 'निरस्यतु', 'Save address': 'पतनं रक्षतु',
    'Loading order details...': 'आदेशविवरणं दृश्यते...', 'Checking your order...': 'भवतः आदेशः परीक्ष्यते...',
    'Order not found': 'आदेशः न प्राप्तः', 'We could not find this order. Check the order link and try again.': 'आदेशः न प्राप्तः। सूत्रं परीक्ष्य पुनः प्रयतताम्।',
    'Order confirmed': 'आदेशः निश्चितः', 'Thank you for your order': 'आदेशाय धन्यवादः',
    'Your order number': 'भवतः आदेशसङ्ख्या', 'was placed on': 'अस्मिन् दिने दत्ता:',
    'Estimated delivery: 2 - 4 business days': 'प्रेषणाय २ तः ४ कार्यदिनानि अपेक्षितानि',
    Customer: 'ग्राहकः', 'Payment details': 'भुगतानविवरणम्', Status: 'स्थितिः',
    'Print receipt': 'रसीदं मुद्रयतु', Quantity: 'परिमाणम्', 'Track order status': 'आदेशस्थितिं पश्यतु',
    'Continue shopping': 'क्रयणं निरन्तरं करोतु',
    'Preparing your kit order...': 'भवतः सञ्चयादेशः सज्जीक्रियते...', 'No puja kit selected': 'पूजासञ्चयः न चयनितः',
    'Choose your puja items before placing the order.': 'आदेशात् पूर्वं पूजावस्तूनि चिनोतु।', 'Open kit builder': 'सञ्चयं रचयतु',
    'Back to kit builder': 'सञ्चयनिर्माणं प्रतिगच्छतु', 'Your kit items': 'भवतः सञ्चयस्य वस्तूनि', 'Edit kit': 'सञ्चयं परिवर्तयतु',
    'Kit price and packing': 'सञ्चयमूल्यं वेष्टनं च', Size: 'आकारः', 'Kit base price': 'सञ्चयस्य आरम्भिकमूल्यम्',
    'Items total': 'वस्तूनां कुलमूल्यम्', 'Delivery takes 3 to 5 business days': 'प्रेषणाय ३ तः ५ कार्यदिनानि अपेक्षितानि',
    'Packed with care in Shri Vishwanath packaging': 'श्रीविश्वनाथवेष्टने सावधानतया वेष्टितम्',
    'Your puja kit is being prepared': 'भवतः पूजासञ्चयः सज्जीक्रियते', 'Estimated delivery: 1 - 3 business days': 'प्रेषणाय १ तः ३ कार्यदिनानि अपेक्षितानि',
    'Kit status': 'सञ्चयस्य स्थितिः', Payment: 'भुगतानम्', 'Total paid': 'कुलभुगतानम्', 'Build another kit': 'अन्यं सञ्चयं रचयतु',
    Description: 'विवरणम्', 'Product details': 'वस्तुविवरणम्', Reviews: 'मतानि',
    'No extra product details are available.': 'अतिरिक्तवस्तुविवरणं न उपलब्धम्।',
    'Product information': 'वस्तुविवरणम्', 'We check product details and share clear information before you buy.': 'क्रयात् पूर्वं वयं वस्तुविवरणं परीक्ष्य स्पष्टसूचनां दद्मः।',
    Source: 'स्रोतः', 'Product details checked': 'वस्तुविवरणं परीक्षितम्',
    Included: 'अन्तर्भूतम्', 'Included in kit price': 'सञ्चयमूल्ये अन्तर्भूतम्', 'Product details unavailable': 'वस्तुविवरणं न उपलब्धम्',
    'First item and delivery are included in the kit price. Extra quantities are charged.': 'प्रथमं वस्तु प्रेषणं च सञ्चयमूल्ये अन्तर्भूतम्। अतिरिक्तपरिमाणस्य मूल्यं देयम्।',
  },
};

Object.assign(translations.hi, checkoutTranslations.hi);
Object.assign(translations.mr, checkoutTranslations.mr);
Object.assign(translations.mwr, checkoutTranslations.mwr);
Object.assign(translations.gu, checkoutTranslations.gu);
Object.assign(translations.sa, checkoutTranslations.sa);

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem(STORAGE_KEY);
    if (savedLanguage && isLanguage(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (nextLanguage: Language) => {
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
    setLanguageState(nextLanguage);
  };

  const t = (text: string) => language === 'en' ? text : translations[language][text] ?? text;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
